[package]
name = "treinamento_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[workspace]
members = [
"app_clientes_console", "coddy/monhtanha-russa", "crates/usar_validador", "crates/validador",  
"desafio-transacoes-rust", 
"desafio-validacao-rust",
"generics", 
"lifetimes", "macros-e-meta",
"polimorfismo_e_impl_trait_vs_dynTrait",
"traits", "traits-1", "tratamento-de-erros",
]
